package com.clients.organiser.models;

import javax.persistence.*;

@Entity
@Table(name="clients")
public class Client {
    // Long id used by Hibernate to map database keys
    @Id
    // Identity type uses auto increment value generated by database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "forename")
    private String forename;

    @Column(name = "surname")
    private String surname;

    @Column(name = "title")
    private String title;

    @Column(name = "type")
    private String type;

    public Client(String forename, String surname, String title, String type) {
        this.forename = forename;
        this.surname = surname;
        this.title = title;
        this.type = type;
    }

    public Client() {
    }

    public Long getId() { return id; }

    public void setId(Long id) { this.id = id; }

    public String getForename() {
        return forename;
    }

    public void setForename(String forename) {
        this.forename = forename;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
