package com.clients.organiser.models;

import javax.persistence.*;

@Entity
@Table(name="clients")
public class Client {
    // Long id used by Hibernate to map database keys
    @Id
    // Identity type uses auto increment value generated by database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name")
    private String name;

    @Column(name = "type")
    private String type;

    public Client (String name, String type) {
        this.name = name;
        this.type = type;
    }

    // Empty constructor for Hibernate
    public Client () {

    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
